var ccb_resources = [
    {type:'ccbi', src:"MainScene.ccbi"},
    {type:'image', src:"Work/W_12.png"},
    {type:'image', src:"Work/W_3.png"},
    {type:'image', src:"bubble.png"},
    {type:'image', src:"cocos2d-html5-logo.png"},
    {type:'image', src:"Work/W_8.png"},
    {type:'image', src:"Work/W_2.png"},
    {type:'image', src:"Work/W_9.png"},
    {type:'image', src:"Work/W_7.png"},
    {type:'image', src:"face.png"},
    {type:'image', src:"Work/W_1.png"},
    {type:'image', src:"blacktocat.png"},
    {type:'image', src:"cocos2d-x.png"},
    {type:'image', src:"Work/W_6.png"},
    {type:'image', src:"Work/W_11.png"},
    {type:'image', src:"Work/W_5.png"},
    {type:'image', src:"Work/W_10.png"},
    {type:'image', src:"Work/W_4.png"},
];
